name: sonorynth
description: Android music player with online playback, playlists, and LRC/QRC/YRC/TTML lyrics.
publish_to: none
version: 1.10.12+46

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  audio_service: ^0.18.19
  audio_session: ^0.2.4
  just_audio: ^0.10.5
  shared_preferences: ^2.5.3
  qr_flutter: ^4.1.0
  crypto: ^3.0.7
  pointycastle: ^4.0.0
  flutter_secure_storage: ^10.0.0
  xml: ^6.6.1
  path_provider: ^2.1.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/effects/oneui_soft_glow_mask.png
